source 'https://rubygems.org'

gem 'rails'
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'bootstrap-sass'
end

gem 'carrierwave'
gem 'carrierwave-mongoid', require: 'carrierwave/mongoid'
gem 'rmagick'
gem 'jquery-rails'
gem 'unicorn'
gem 'sorcery'
gem 'mongoid'
gem 'bson_ext'
gem 'decent_exposure'
gem 'inherited_resources'
gem 'haml'
gem 'nokogiri'
gem 'rest-open-uri'
gem 'juggernaut'
gem 'uuid'
gem 'stalker'
gem 'pry'
gem 'less'
gem 'mechanize'
gem 'ratom'
gem 'gravtastic'
gem 'garb'
gem 'oauth'
gem 'pony'
gem 'embedly'
gem 'clockwork'
gem 'libarchive'
gem 'foreman'
gem 'bitly'
gem 'httparty'
gem 'leftronic'
gem 'postmark'
gem 'postmark-rails'
gem 'stripe'
