source 'https://rubygems.org'

gem 'rails'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.0'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'unicorn'
gem 'sorcery'
gem 'mongoid'
gem 'bson_ext'
gem 'decent_exposure'
gem 'inherited_resources'
gem 'haml'
gem 'nokogiri'
gem 'rest-open-uri'
gem 'juggernaut'
gem 'uuid'
gem 'stalker'
gem 'pry'
gem 'less'
gem 'mechanize'
gem 'ratom'
gem 'gravtastic'
